// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EF7.MigrationBug.Migrations
{
    [DbContext(typeof(DbCtx))]
    partial class DbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Root", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Table");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Root");
                });

            modelBuilder.Entity("Child", b =>
                {
                    b.HasBaseType("Root");

                    b.HasDiscriminator().HasValue("Child");
                });

            modelBuilder.Entity("GrandChild", b =>
                {
                    b.HasBaseType("Child");

                    b.Property<Guid>("ParentUserId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("GrandChild");
                });
#pragma warning restore 612, 618
        }
    }
}
